const presentData = [
    {
        infinitive: 'correr',
        infinitive_english: 'to run',
        mood: 'Indicativo',
        mood_english: 'Indicative',
        tense: 'Presente',
        tense_english: 'Present',
        verb_english: 'I run, am running',
        form_1s: 'corro',
        form_2s: 'corres',
        form_3s: 'corre',
        form_1p: 'corremos',
        form_2p: 'corréis',
        form_3p: 'corren',
        gerund: 'corriendo',
        gerund_english: 'running',
        pastparticiple: 'corrido',
        pastparticiple_english: 'run'
    },
    {
        infinitive: 'venir',
        infinitive_english: 'to come',
        mood: 'Indicativo',
        mood_english: 'Indicative',
        tense: 'Presente',
        tense_english: 'Present',
        verb_english: 'I come, am coming',
        form_1s: 'vengo',
        form_2s: 'vienes',
        form_3s: 'viene',
        form_1p: 'venimos',
        form_2p: 'venís',
        form_3p: 'vienen',
        gerund: 'viniendo',
        gerund_english: 'coming',
        pastparticiple: 'venido',
        pastparticiple_english: 'come'
    },
    {
        infinitive: 'decir',
        infinitive_english: 'to say, tell',
        mood: 'Indicativo',
        mood_english: 'Indicative',
        tense: 'Presente',
        tense_english: 'Present',
        verb_english: 'I say, am saying',
        form_1s: 'digo',
        form_2s: 'dices',
        form_3s: 'dice',
        form_1p: 'decimos',
        form_2p: 'decís',
        form_3p: 'dicen',
        gerund: 'diciendo',
        gerund_english: 'saying',
        pastparticiple: 'dicho',
        pastparticiple_english: 'said'
    },
    {
        infinitive: 'poder',
        infinitive_english: 'to be able, can',
        mood: 'Indicativo',
        mood_english: 'Indicative',
        tense: 'Presente',
        tense_english: 'Present',
        verb_english: 'I am able, can',
        form_1s: 'puedo',
        form_2s: 'puedes',
        form_3s: 'puede',
        form_1p: 'podemos',
        form_2p: 'podéis',
        form_3p: 'pueden',
        gerund: 'pudiendo',
        gerund_english: 'being able',
        pastparticiple: 'podido',
        pastparticiple_english: 'been able'
    },
    {
        infinitive: 'dar',
        infinitive_english: 'to give',
        mood: 'Indicativo',
        mood_english: 'Indicative',
        tense: 'Presente',
        tense_english: 'Present',
        verb_english: 'I give, am giving',
        form_1s: 'doy',
        form_2s: 'das',
        form_3s: 'da',
        form_1p: 'damos',
        form_2p: 'dais',
        form_3p: 'dan',
        gerund: 'dando',
        gerund_english: 'giving',
        pastparticiple: 'dado',
        pastparticiple_english: 'given'
    },
    {
        infinitive: 'ver',
        infinitive_english: 'to see',
        mood: 'Indicativo',
        mood_english: 'Indicative',
        tense: 'Presente',
        tense_english: 'Present',
        verb_english: 'I see, am seeing',
        form_1s: 'veo',
        form_2s: 'ves',
        form_3s: 've',
        form_1p: 'vemos',
        form_2p: 'veis',
        form_3p: 'ven',
        gerund: 'viendo',
        gerund_english: 'seeing',
        pastparticiple: 'visto',
        pastparticiple_english: 'seen'
    },
    {
        infinitive: 'saber',
        infinitive_english: 'to know',
        mood: 'Indicativo',
        mood_english: 'Indicative',
        tense: 'Presente',
        tense_english: 'Present',
        verb_english: 'I know',
        form_1s: 'sé',
        form_2s: 'sabes',
        form_3s: 'sabe',
        form_1p: 'sabemos',
        form_2p: 'sabéis',
        form_3p: 'saben',
        gerund: 'sabiendo',
        gerund_english: 'knowing',
        pastparticiple: 'sabido',
        pastparticiple_english: 'known'
    },
    {
        infinitive: 'hablar',
        infinitive_english: 'to speak',
        mood: 'Indicativo',
        mood_english: 'Indicative',
        tense: 'Presente',
        tense_english: 'Present',
        verb_english: 'I speak, am speaking',
        form_1s: 'hablo',
        form_2s: 'hablas',
        form_3s: 'habla',
        form_1p: 'hablamos',
        form_2p: 'habláis',
        form_3p: 'hablan',
        gerund: 'hablando',
        gerund_english: 'speaking',
        pastparticiple: 'hablado',
        pastparticiple_english: 'spoken'
    },
    {
        infinitive: 'estar',
        infinitive_english: 'to be',
        mood: 'Indicativo',
        mood_english: 'Indicative',
        tense: 'Presente',
        tense_english: 'Present',
        verb_english: 'I am',
        form_1s: 'estoy',
        form_2s: 'estás',
        form_3s: 'está',
        form_1p: 'estamos',
        form_2p: 'estáis',
        form_3p: 'están',
        gerund: 'estando',
        gerund_english: 'being',
        pastparticiple: 'estado',
        pastparticiple_english: 'been'
    },
    {
        infinitive: 'ser',
        infinitive_english: 'to be',
        mood: 'Indicativo',
        mood_english: 'Indicative',
        tense: 'Presente',
        tense_english: 'Present',
        verb_english: 'I am',
        form_1s: 'soy',
        form_2s: 'eres',
        form_3s: 'es',
        form_1p: 'somos',
        form_2p: 'sois',
        form_3p: 'son',
        gerund: 'siendo',
        gerund_english: 'being',
        pastparticiple: 'sido',
        pastparticiple_english: 'been'
    },
    {
        infinitive: 'tener',
        infinitive_english: 'to have',
        mood: 'Indicativo',
        mood_english: 'Indicative',
        tense: 'Presente',
        tense_english: 'Present',
        verb_english: 'I have, am having',
        form_1s: 'tengo',
        form_2s: 'tienes',
        form_3s: 'tiene',
        form_1p: 'tenemos',
        form_2p: 'tenéis',
        form_3p: 'tienen',
        gerund: 'teniendo',
        gerund_english: 'having',
        pastparticiple: 'tenido',
        pastparticiple_english: 'had'
    },
    {
        infinitive: 'hacer',
        infinitive_english: 'to do, make',
        mood: 'Indicativo',
        mood_english: 'Indicative',
        tense: 'Presente',
        tense_english: 'Present',
        verb_english: 'I do, am doing',
        form_1s: 'hago',
        form_2s: 'haces',
        form_3s: 'hace',
        form_1p: 'hacemos',
        form_2p: 'hacéis',
        form_3p: 'hacen',
        gerund: 'haciendo',
        gerund_english: 'doing',
        pastparticiple: 'hecho',
        pastparticiple_english: 'done'
    },
    {
        infinitive: 'ir',
        infinitive_english: 'to go',
        mood: 'Indicativo',
        mood_english: 'Indicative',
        tense: 'Presente',
        tense_english: 'Present',
        verb_english: 'I go, am going',
        form_1s: 'voy',
        form_2s: 'vas',
        form_3s: 'va',
        form_1p: 'vamos',
        form_2p: 'vais',
        form_3p: 'van',
        gerund: 'yendo',
        gerund_english: 'going',
        pastparticiple: 'ido',
        pastparticiple_english: 'gone'
    },
    {
        infinitive: "alquilar",
        infinitive_english: "to rent; to rent out, let",
        mood: "Indicativo",
        mood_english: "Indicative",
        tense: "Presente",
        tense_english: "Present",
        verb_english: "I rent, am renting",
        form_1s: "alquilo",
        form_2s: "alquilas",
        form_3s: "alquila",
        form_1p: "alquilamos",
        form_2p: "alquiláis",
        form_3p: "alquilan",
        gerund: "alquilando",
        gerund_english: "renting",
        pastparticiple: "alquilado",
        pastparticiple_english: "rented"
    },
    {
        infinitive: "necesitar",
        infinitive_english: "to need, require",
        mood: "Indicativo",
        mood_english: "Indicative",
        tense: "Presente",
        tense_english: "Present",
        verb_english: "I need, am needing",
        form_1s: "necesito",
        form_2s: "necesitas",
        form_3s: "necesita",
        form_1p: "necesitamos",
        form_2p: "necesitáis",
        form_3p: "necesitan",
        gerund: "necesitando",
        gerund_english: "needing",
        pastparticiple: "necesitado",
        pastparticiple_english: "needed"
    },
    {
        infinitive: "amar",
        infinitive_english: "to love",
        mood: "Indicativo",
        mood_english: "Indicative",
        tense: "Presente",
        tense_english: "Present",
        verb_english: "I love, am loving",
        form_1s: "amo",
        form_2s: "amas",
        form_3s: "ama",
        form_1p: "amamos",
        form_2p: "amáis",
        form_3p: "aman",
        gerund: "amando",
        gerund_english: "loving",
        pastparticiple: "amado",
        pastparticiple_english: "loved"
    },
    {
        infinitive: "enviar",
        infinitive_english: "to send",
        mood: "Indicativo",
        mood_english: "Indicative",
        tense: "Presente",
        tense_english: "Present",
        verb_english: "I send, am sending",
        form_1s: "envío",
        form_2s: "envías",
        form_3s: "envía",
        form_1p: "enviamos",
        form_2p: "enviáis",
        form_3p: "envían",
        gerund: "enviando",
        gerund_english: "sending",
        pastparticiple: "enviado",
        pastparticiple_english: "sent"
    },
    {
        infinitive: "olvidar",
        infinitive_english: "to forget",
        mood: "Indicativo",
        mood_english: "Indicative",
        tense: "Presente",
        tense_english: "Present",
        verb_english: "I forget, am forgetting",
        form_1s: "olvido",
        form_2s: "olvidas",
        form_3s: "olvida",
        form_1p: "olvidamos",
        form_2p: "olvidáis",
        form_3p: "olvidan",
        gerund: "olvidando",
        gerund_english: "forgetting",
        pastparticiple: "olvidado",
        pastparticiple_english: "forgotten"
    },
    {
        infinitive: "andar",
        infinitive_english: "to walk, go",
        mood: "Indicativo",
        mood_english: "Indicative",
        tense: "Presente",
        tense_english: "Present",
        verb_english: "I walk, am walking",
        form_1s: "ando",
        form_2s: "andas",
        form_3s: "anda",
        form_1p: "andamos",
        form_2p: "andáis",
        form_3p: "andan",
        gerund: "andando",
        gerund_english: "walking",
        pastparticiple: "andado",
        pastparticiple_english: "walked"
    },
    {
        infinitive: "escuchar",
        infinitive_english: "to listen to, hear",
        mood: "Indicativo",
        mood_english: "Indicative",
        tense: "Presente",
        tense_english: "Present",
        verb_english: "I listen to, am listening to",
        form_1s: "escucho",
        form_2s: "escuchas",
        form_3s: "escucha",
        form_1p: "escuchamos",
        form_2p: "escucháis",
        form_3p: "escuchan",
        gerund: "escuchando",
        gerund_english: "listening to",
        pastparticiple: "escuchado",
        pastparticiple_english: "listened to"
    },
    {
        infinitive: "pagar",
        infinitive_english: "to pay, pay for",
        mood: "Indicativo",
        mood_english: "Indicative",
        tense: "Presente",
        tense_english: "Present",
        verb_english: "I pay, am paying",
        form_1s: "pago",
        form_2s: "pagas",
        form_3s: "paga",
        form_1p: "pagamos",
        form_2p: "pagáis",
        form_3p: "pagan",
        gerund: "pagando",
        gerund_english: "paying",
        pastparticiple: "pagado",
        pastparticiple_english: "paid"
    },
    {
        infinitive: "ayudar",
        infinitive_english: "to help",
        mood: "Indicativo",
        mood_english: "Indicative",
        tense: "Presente",
        tense_english: "Present",
        verb_english: "I help, am helping",
        form_1s: "ayudo",
        form_2s: "ayudas",
        form_3s: "ayuda",
        form_1p: "ayudamos",
        form_2p: "ayudáis",
        form_3p: "ayudan",
        gerund: "ayudando",
        gerund_english: "helping",
        pastparticiple: "ayudado",
        pastparticiple_english: "helped"
    },
    {
        infinitive: "esperar",
        infinitive_english: "to hope",
        mood: "Indicativo",
        mood_english: "Indicative",
        tense: "Presente",
        tense_english: "Present",
        verb_english: "I hope, am hoping",
        form_1s: "espero",
        form_2s: "esperas",
        form_3s: "espera",
        form_1p: "esperamos",
        form_2p: "esperáis",
        form_3p: "esperan",
        gerund: "esperando",
        gerund_english: "hoping",
        pastparticiple: "esperado",
        pastparticiple_english: "hoped"
    },
    {
        infinitive: "practicar",
        infinitive_english: "to practice",
        mood: "Indicativo",
        mood_english: "Indicative",
        tense: "Presente",
        tense_english: "Present",
        verb_english: "I practice, am practicing",
        form_1s: "practico",
        form_2s: "practicas",
        form_3s: "practica",
        form_1p: "practicamos",
        form_2p: "practicáis",
        form_3p: "practican",
        gerund: "practicando",
        gerund_english: "practicing",
        pastparticiple: "practicado",
        pastparticiple_english: "practiced"
    },
    {
        infinitive: "bailar",
        infinitive_english: "dance",
        mood: "Indicativo",
        mood_english: "Indicative",
        tense: "Presente",
        tense_english: "Present",
        verb_english: "I dance, am dancing",
        form_1s: "bailo",
        form_2s: "bailas",
        form_3s: "baila",
        form_1p: "bailamos",
        form_2p: "bailáis",
        form_3p: "bailan",
        gerund: "bailando",
        gerund_english: "dancing",
        pastparticiple: "bailado",
        pastparticiple_english: "danced"
    },
    {
        infinitive: "estudiar",
        infinitive_english: "to study",
        mood: "Indicativo",
        mood_english: "Indicative",
        tense: "Presente",
        tense_english: "Present",
        verb_english: "I study, am studying",
        form_1s: "estudio",
        form_2s: "estudias",
        form_3s: "estudia",
        form_1p: "estudiamos",
        form_2p: "estudiáis",
        form_3p: "estudian",
        gerund: "estudiando",
        gerund_english: "studying",
        pastparticiple: "estudiado",
        pastparticiple_english: "studied"
    },
    {
        infinitive: "preguntar",
        infinitive_english: "to ask, inquire",
        mood: "Indicativo",
        mood_english: "Indicative",
        tense: "Presente",
        tense_english: "Present",
        verb_english: "I ask, am asking",
        form_1s: "pregunto",
        form_2s: "preguntas",
        form_3s: "pregunta",
        form_1p: "preguntamos",
        form_2p: "preguntáis",
        form_3p: "preguntan",
        gerund: "preguntando",
        gerund_english: "asking",
        pastparticiple: "preguntado",
        pastparticiple_english: "asked"
    },
    {
        infinitive: "buscar",
        infinitive_english: "to search for, look for",
        mood: "Indicativo",
        mood_english: "Indicative",
        tense: "Presente",
        tense_english: "Present",
        verb_english: "I search for, am searching for",
        form_1s: "busco",
        form_2s: "buscas",
        form_3s: "busca",
        form_1p: "buscamos",
        form_2p: "buscáis",
        form_3p: "buscan",
        gerund: "buscando",
        gerund_english: "searching for",
        pastparticiple: "buscado",
        pastparticiple_english: "searched for"
    },
    {
        infinitive: "firmar",
        infinitive_english: "to sign",
        mood: "Indicativo",
        mood_english: "Indicative",
        tense: "Presente",
        tense_english: "Present",
        verb_english: "I sign, am signing",
        form_1s: "firmo",
        form_2s: "firmas",
        form_3s: "firma",
        form_1p: "firmamos",
        form_2p: "firmáis",
        form_3p: "firman",
        gerund: "firmando",
        gerund_english: "signing",
        pastparticiple: "firmado",
        pastparticiple_english: "signed"
    },
    {
        infinitive: "preparar",
        infinitive_english: "to prepare",
        mood: "Indicativo",
        mood_english: "Indicative",
        tense: "Presente",
        tense_english: "Present",
        verb_english: "I prepare, am preparing",
        form_1s: "preparo",
        form_2s: "preparas",
        form_3s: "prepara",
        form_1p: "preparamos",
        form_2p: "preparáis",
        form_3p: "preparan",
        gerund: "preparando",
        gerund_english: "preparing",
        pastparticiple: "preparado",
        pastparticiple_english: "prepared"
    },
    {
        infinitive: "caminar",
        infinitive_english: "to walk, go",
        mood: "Indicativo",
        mood_english: "Indicative",
        tense: "Presente",
        tense_english: "Present",
        verb_english: "I walk, am walking",
        form_1s: "camino",
        form_2s: "caminas",
        form_3s: "camina",
        form_1p: "caminamos",
        form_2p: "camináis",
        form_3p: "caminan",
        gerund: "caminando",
        gerund_english: "walking",
        pastparticiple: "caminado",
        pastparticiple_english: "walked"
    },
    {
        infinitive: "ganar",
        infinitive_english: "to win, gain, earn, get, acquire",
        mood: "Indicativo",
        mood_english: "Indicative",
        tense: "Presente",
        tense_english: "Present",
        verb_english: "I win, am winning",
        form_1s: "gano",
        form_2s: "ganas",
        form_3s: "gana",
        form_1p: "ganamos",
        form_2p: "ganáis",
        form_3p: "ganan",
        gerund: "ganando",
        gerund_english: "winning",
        pastparticiple: "ganado",
        pastparticiple_english: "won"
    },
    {
        infinitive: "regresar",
        infinitive_english: "to return, go back",
        mood: "Indicativo",
        mood_english: "Indicative",
        tense: "Presente",
        tense_english: "Present",
        verb_english: "I return, am returning",
        form_1s: "regreso",
        form_2s: "regresas",
        form_3s: "regresa",
        form_1p: "regresamos",
        form_2p: "regresáis",
        form_3p: "regresan",
        gerund: "regresando",
        gerund_english: "returning",
        pastparticiple: "regresado",
        pastparticiple_english: "returned"
    },
    {
        infinitive: "gastar",
        infinitive_english: "to spend, expend; to use up, consume; to wear away, wear down",
        mood: "Indicativo",
        mood_english: "Indicative",
        tense: "Presente",
        tense_english: "Present",
        verb_english: "I spend, am spending",
        form_1s: "gasto",
        form_2s: "gastas",
        form_3s: "gasta",
        form_1p: "gastamos",
        form_2p: "gastáis",
        form_3p: "gastan",
        gerund: "gastando",
        gerund_english: "spending",
        pastparticiple: "gastado",
        pastparticiple_english: "spent"
    },
    {
        infinitive: "saludar",
        infinitive_english: "to greet, salute, hail, welcome",
        mood: "Indicativo",
        mood_english: "Indicative",
        tense: "Presente",
        tense_english: "Present",
        verb_english: "I greet, am greeting",
        form_1s: "saludo",
        form_2s: "saludas",
        form_3s: "saluda",
        form_1p: "saludamos",
        form_2p: "saludáis",
        form_3p: "saludan",
        gerund: "saludando",
        gerund_english: "greeting",
        pastparticiple: "saludado",
        pastparticiple_english: "greeted"
    },
    {
        infinitive: "cocinar",
        infinitive_english: "to cook; to do the cooking",
        mood: "Indicativo",
        mood_english: "Indicative",
        tense: "Presente",
        tense_english: "Present",
        verb_english: "I cook, am cooking",
        form_1s: "cocino",
        form_2s: "cocinas",
        form_3s: "cocina",
        form_1p: "cocinamos",
        form_2p: "cocináis",
        form_3p: "cocinan",
        gerund: "cocinando",
        gerund_english: "cooking",
        pastparticiple: "cocinado",
        pastparticiple_english: "cooked"
    },
    {
        infinitive: "tocar",
        infinitive_english: "to touch; to play",
        mood: "Indicativo",
        mood_english: "Indicative",
        tense: "Presente",
        tense_english: "Present",
        verb_english: "I touch, am touching",
        form_1s: "toco",
        form_2s: "tocas",
        form_3s: "toca",
        form_1p: "tocamos",
        form_2p: "tocáis",
        form_3p: "tocan",
        gerund: "tocando",
        gerund_english: "touching",
        pastparticiple: "tocado",
        pastparticiple_english: "touched"
    },
    {
        infinitive: "comprar",
        infinitive_english: "to buy, purchase",
        mood: "Indicativo",
        mood_english: "Indicative",
        tense: "Presente",
        tense_english: "Present",
        verb_english: "I buy, am buying",
        form_1s: "compro",
        form_2s: "compras",
        form_3s: "compra",
        form_1p: "compramos",
        form_2p: "compráis",
        form_3p: "compran",
        gerund: "comprando",
        gerund_english: "buying",
        pastparticiple: "comprado",
        pastparticiple_english: "bought"
    },
    {
        infinitive: "lavar",
        infinitive_english: "to wash",
        mood: "Indicativo",
        mood_english: "Indicative",
        tense: "Presente",
        tense_english: "Present",
        verb_english: "I wash, am washing",
        form_1s: "lavo",
        form_2s: "lavas",
        form_3s: "lava",
        form_1p: "lavamos",
        form_2p: "laváis",
        form_3p: "lavan",
        gerund: "lavando",
        gerund_english: "washing",
        pastparticiple: "lavado",
        pastparticiple_english: "washed"
    },
    {
        infinitive: "tomar",
        infinitive_english: "to take, drink",
        mood: "Indicativo",
        mood_english: "Indicative",
        tense: "Presente",
        tense_english: "Present",
        verb_english: "I take, am taking",
        form_1s: "tomo",
        form_2s: "tomas",
        form_3s: "toma",
        form_1p: "tomamos",
        form_2p: "tomáis",
        form_3p: "toman",
        gerund: "tomando",
        gerund_english: "taking",
        pastparticiple: "tomado",
        pastparticiple_english: "taken"
    },
    {
        infinitive: "contestar",
        infinitive_english: "to answer",
        mood: "Indicativo",
        mood_english: "Indicative",
        tense: "Presente",
        tense_english: "Present",
        verb_english: "I answer, am answering",
        form_1s: "contesto",
        form_2s: "contestas",
        form_3s: "contesta",
        form_1p: "contestamos",
        form_2p: "contestáis",
        form_3p: "contestan",
        gerund: "contestando",
        gerund_english: "answering",
        pastparticiple: "contestado",
        pastparticiple_english: "answered"
    },
    {
        infinitive: "llegar",
        infinitive_english: "to arrive, come, reach; to bring up, bring over; to gather together",
        mood: "Indicativo",
        mood_english: "Indicative",
        tense: "Presente",
        tense_english: "Present",
        verb_english: "I arrive, am arriving",
        form_1s: "llego",
        form_2s: "llegas",
        form_3s: "llega",
        form_1p: "llegamos",
        form_2p: "llegáis",
        form_3p: "llegan",
        gerund: "llegando",
        gerund_english: "arriving",
        pastparticiple: "llegado",
        pastparticiple_english: "arrived"
    },
    {
        infinitive: "trabajar",
        infinitive_english: "to work",
        mood: "Indicativo",
        mood_english: "Indicative",
        tense: "Presente",
        tense_english: "Present",
        verb_english: "I work, am working",
        form_1s: "trabajo",
        form_2s: "trabajas",
        form_3s: "trabaja",
        form_1p: "trabajamos",
        form_2p: "trabajáis",
        form_3p: "trabajan",
        gerund: "trabajando",
        gerund_english: "working",
        pastparticiple: "trabajado",
        pastparticiple_english: "worked"
    },
    {
        infinitive: "dejar",
        infinitive_english: "to leave, abandon; to let, allow",
        mood: "Indicativo",
        mood_english: "Indicative",
        tense: "Presente",
        tense_english: "Present",
        verb_english: "I leave, am leaving",
        form_1s: "dejo",
        form_2s: "dejas",
        form_3s: "deja",
        form_1p: "dejamos",
        form_2p: "dejáis",
        form_3p: "dejan",
        gerund: "dejando",
        gerund_english: "leaving",
        pastparticiple: "dejado",
        pastparticiple_english: "left"
    },
    {
        infinitive: "llevar",
        infinitive_english: "to carry, bring",
        mood: "Indicativo",
        mood_english: "Indicative",
        tense: "Presente",
        tense_english: "Present",
        verb_english: "I carry, am carrying",
        form_1s: "llevo",
        form_2s: "llevas",
        form_3s: "lleva",
        form_1p: "llevamos",
        form_2p: "lleváis",
        form_3p: "llevan",
        gerund: "llevando",
        gerund_english: "carrying",
        pastparticiple: "llevado",
        pastparticiple_english: "carried"
    },
    {
        infinitive: "viajar",
        infinitive_english: "to travel, journey",
        mood: "Indicativo",
        mood_english: "Indicative",
        tense: "Presente",
        tense_english: "Present",
        verb_english: "I travel, am traveling",
        form_1s: "viajo",
        form_2s: "viajas",
        form_3s: "viaja",
        form_1p: "viajamos",
        form_2p: "viajáis",
        form_3p: "viajan",
        gerund: "viajando",
        gerund_english: "traveling",
        pastparticiple: "viajado",
        pastparticiple_english: "traveled"
    },
    {
        infinitive: "desear",
        infinitive_english: "to desire, want, wish",
        mood: "Indicativo",
        mood_english: "Indicative",
        tense: "Presente",
        tense_english: "Present",
        verb_english: "I desire, am desiring",
        form_1s: "deseo",
        form_2s: "deseas",
        form_3s: "desea",
        form_1p: "deseamos",
        form_2p: "deseáis",
        form_3p: "desean",
        gerund: "deseando",
        gerund_english: "desiring",
        pastparticiple: "deseado",
        pastparticiple_english: "desired"
    },
    {
        infinitive: "mandar",
        infinitive_english: "to order",
        mood: "Indicativo",
        mood_english: "Indicative",
        tense: "Presente",
        tense_english: "Present",
        verb_english: "I order, am ordering",
        form_1s: "mando",
        form_2s: "mandas",
        form_3s: "manda",
        form_1p: "mandamos",
        form_2p: "mandáis",
        form_3p: "mandan",
        gerund: "mandando",
        gerund_english: "ordering",
        pastparticiple: "mandado",
        pastparticiple_english: "ordered"
    },
    {
        infinitive: "visitar",
        infinitive_english: "to visit",
        mood: "Indicativo",
        mood_english: "Indicative",
        tense: "Presente",
        tense_english: "Present",
        verb_english: "I visit, am visiting",
        form_1s: "visito",
        form_2s: "visitas",
        form_3s: "visita",
        form_1p: "visitamos",
        form_2p: "visitáis",
        form_3p: "visitan",
        gerund: "visitando",
        gerund_english: "visiting",
        pastparticiple: "visitado",
        pastparticiple_english: "visited"
    },
    {
        infinitive: "enseñar",
        infinitive_english: "to teach, instruct, train, educate",
        mood: "Indicativo",
        mood_english: "Indicative",
        tense: "Presente",
        tense_english: "Present",
        verb_english: "I teach, am teaching",
        form_1s: "enseño",
        form_2s: "enseñas",
        form_3s: "enseña",
        form_1p: "enseñamos",
        form_2p: "enseñáis",
        form_3p: "enseñan",
        gerund: "enseñando",
        gerund_english: "teaching",
        pastparticiple: "enseñado",
        pastparticiple_english: "taught"
    },
    {
        infinitive: "mirar",
        infinitive_english: "to watch, look at",
        mood: "Indicativo",
        mood_english: "Indicative",
        tense: "Presente",
        tense_english: "Present",
        verb_english: "I watch, am watching",
        form_1s: "miro",
        form_2s: "miras",
        form_3s: "mira",
        form_1p: "miramos",
        form_2p: "miráis",
        form_3p: "miran",
        gerund: "mirando",
        gerund_english: "watching",
        pastparticiple: "mirado",
        pastparticiple_english: "watched"
    },
    {
        infinitive: "aprender",
        infinitive_english: "to learn",
        mood: "Indicativo",
        mood_english: "Indicative",
        tense: "Presente",
        tense_english: "Present",
        verb_english: "I learn, am learning",
        form_1s: "aprendo",
        form_2s: "aprendes",
        form_3s: "aprende",
        form_1p: "aprendemos",
        form_2p: "aprendéis",
        form_3p: "aprenden",
        gerund: "aprendiendo",
        gerund_english: "learning",
        pastparticiple: "aprendido",
        pastparticiple_english: "learned"
    },
    {
        infinitive: "creer",
        infinitive_english: "to believe",
        mood: "Indicativo",
        mood_english: "Indicative",
        tense: "Presente",
        tense_english: "Present",
        verb_english: "I believe, am believing",
        form_1s: "creo",
        form_2s: "crees",
        form_3s: "cree",
        form_1p: "creemos",
        form_2p: "creéis",
        form_3p: "creen",
        gerund: "creyendo",
        gerund_english: "believing",
        pastparticiple: "creído",
        pastparticiple_english: "believed"
    },
    {
        infinitive: "responder",
        infinitive_english: "to respond, answer, reply to",
        mood: "Indicativo",
        mood_english: "Indicative",
        tense: "Presente",
        tense_english: "Present",
        verb_english: "I respond, am responding",
        form_1s: "respondo",
        form_2s: "respondes",
        form_3s: "responde",
        form_1p: "respondemos",
        form_2p: "respondéis",
        form_3p: "responden",
        gerund: "respondiendo",
        gerund_english: "responding",
        pastparticiple: "respondido",
        pastparticiple_english: "responded"
    },
    {
        infinitive: "beber",
        infinitive_english: "to drink",
        mood: "Indicativo",
        mood_english: "Indicative",
        tense: "Presente",
        tense_english: "Present",
        verb_english: "I drink, am drinking",
        form_1s: "bebo",
        form_2s: "bebes",
        form_3s: "bebe",
        form_1p: "bebemos",
        form_2p: "bebéis",
        form_3p: "beben",
        gerund: "bebiendo",
        gerund_english: "drinking",
        pastparticiple: "bebido",
        pastparticiple_english: "drunk"
    },
    {
        infinitive: "deber",
        infinitive_english: "to have to; to owe",
        mood: "Indicativo",
        mood_english: "Indicative",
        tense: "Presente",
        tense_english: "Present",
        verb_english: "I owe, am owing",
        form_1s: "debo",
        form_2s: "debes",
        form_3s: "debe",
        form_1p: "debemos",
        form_2p: "debéis",
        form_3p: "deben",
        gerund: "debiendo",
        gerund_english: "owing",
        pastparticiple: "debido",
        pastparticiple_english: "owed"
    },
    {
        infinitive: "prometer",
        infinitive_english: "to promise",
        mood: "Indicativo",
        mood_english: "Indicative",
        tense: "Presente",
        tense_english: "Present",
        verb_english: "I promise, am promising",
        form_1s: "prometo",
        form_2s: "prometes",
        form_3s: "promete",
        form_1p: "prometemos",
        form_2p: "prometéis",
        form_3p: "prometen",
        gerund: "prometiendo",
        gerund_english: "promising",
        pastparticiple: "prometido",
        pastparticiple_english: "promised"
    },
    {
        infinitive: "comer",
        infinitive_english: "to eat",
        mood: "Indicativo",
        mood_english: "Indicative",
        tense: "Presente",
        tense_english: "Present",
        verb_english: "I eat, am eating",
        form_1s: "como",
        form_2s: "comes",
        form_3s: "come",
        form_1p: "comemos",
        form_2p: "coméis",
        form_3p: "comen",
        gerund: "comiendo",
        gerund_english: "eating",
        pastparticiple: "comido",
        pastparticiple_english: "eaten"
    },
    {
        infinitive: "esconder",
        infinitive_english: "to hide, conceal",
        mood: "Indicativo",
        mood_english: "Indicative",
        tense: "Presente",
        tense_english: "Present",
        verb_english: "I hide, am hiding",
        form_1s: "escondo",
        form_2s: "escondes",
        form_3s: "esconde",
        form_1p: "escondemos",
        form_2p: "escondéis",
        form_3p: "esconden",
        gerund: "escondiendo",
        gerund_english: "hiding",
        pastparticiple: "escondido",
        pastparticiple_english: "hiddenk"
    },
    {
        infinitive: "romper",
        infinitive_english: "to break",
        mood: "Indicativo",
        mood_english: "Indicative",
        tense: "Presente",
        tense_english: "Present",
        verb_english: "I break, am breaking",
        form_1s: "rompo",
        form_2s: "rompes",
        form_3s: "rompe",
        form_1p: "rompemos",
        form_2p: "rompéis",
        form_3p: "rompen",
        gerund: "rompiendo",
        gerund_english: "breaking",
        pastparticiple: "roto",
        pastparticiple_english: "broken"
    },
    {
        infinitive: "comprender",
        infinitive_english: "to understand, comprehend",
        mood: "Indicativo",
        mood_english: "Indicative",
        tense: "Presente",
        tense_english: "Present",
        verb_english: "I understand, am understanding",
        form_1s: "comprendo",
        form_2s: "comprendes",
        form_3s: "comprende",
        form_1p: "comprendemos",
        form_2p: "comprendéis",
        form_3p: "comprenden",
        gerund: "comprendiendo",
        gerund_english: "understanding",
        pastparticiple: "comprendido",
        pastparticiple_english: "understood"
    },
    {
        infinitive: "leer",
        infinitive_english: "to read",
        mood: "Indicativo",
        mood_english: "Indicative",
        tense: "Presente",
        tense_english: "Present",
        verb_english: "I read, am reading",
        form_1s: "leo",
        form_2s: "lees",
        form_3s: "lee",
        form_1p: "leemos",
        form_2p: "leéis",
        form_3p: "leen",
        gerund: "leyendo",
        gerund_english: "reading",
        pastparticiple: "leído",
        pastparticiple_english: "read"
    },
    {
        infinitive: "temer",
        infinitive_english: "to fear",
        mood: "Indicativo",
        mood_english: "Indicative",
        tense: "Presente",
        tense_english: "Present",
        verb_english: "I fear, am fearing",
        form_1s: "temo",
        form_2s: "temes",
        form_3s: "teme",
        form_1p: "tememos",
        form_2p: "teméis",
        form_3p: "temen",
        gerund: "temiendo",
        gerund_english: "fearing",
        pastparticiple: "temido",
        pastparticiple_english: "feared"
    },
    {
        infinitive: "meter",
        infinitive_english: "to put [in], place, insert",
        mood: "Indicativo",
        mood_english: "Indicative",
        tense: "Presente",
        tense_english: "Present",
        verb_english: "I put, am putting",
        form_1s: "meto",
        form_2s: "metes",
        form_3s: "mete",
        form_1p: "metemos",
        form_2p: "metéis",
        form_3p: "meten",
        gerund: "metiendo",
        gerund_english: "putting",
        pastparticiple: "metido",
        pastparticiple_english: "put"
    },
    {
        infinitive: "vender",
        infinitive_english: "to sell",
        mood: "Indicativo",
        mood_english: "Indicative",
        tense: "Presente",
        tense_english: "Present",
        verb_english: "I sell, am selling",
        form_1s: "vendo",
        form_2s: "vendes",
        form_3s: "vende",
        form_1p: "vendemos",
        form_2p: "vendéis",
        form_3p: "venden",
        gerund: "vendiendo",
        gerund_english: "selling",
        pastparticiple: "vendido",
        pastparticiple_english: "sold"
    },
    {
        infinitive: "escoger",
        infinitive_english: "to choose, select, pick",
        mood: "Indicativo",
        mood_english: "Indicative",
        tense: "Presente",
        tense_english: "Present",
        verb_english: "I choose, am choosing",
        form_1s: "escojo",
        form_2s: "escoges",
        form_3s: "escoge",
        form_1p: "escogemos",
        form_2p: "escogéis",
        form_3p: "escogen",
        gerund: "escogiendo",
        gerund_english: "choosing",
        pastparticiple: "escogido",
        pastparticiple_english: "chosen"
    },
    {
        infinitive: "abrir",
        infinitive_english: "to open",
        mood: "Indicativo",
        mood_english: "Indicative",
        tense: "Presente",
        tense_english: "Present",
        verb_english: "I open, am opening",
        form_1s: "abro",
        form_2s: "abres",
        form_3s: "abre",
        form_1p: "abrimos",
        form_2p: "abrís",
        form_3p: "abren",
        gerund: "abriendo",
        gerund_english: "opening",
        pastparticiple: "abierto",
        pastparticiple_english: "opened"
    },
    {
        infinitive: "descubrir",
        infinitive_english: "to discover",
        mood: "Indicativo",
        mood_english: "Indicative",
        tense: "Presente",
        tense_english: "Present",
        verb_english: "I discover, am discovering",
        form_1s: "descubro",
        form_2s: "descubres",
        form_3s: "descubre",
        form_1p: "descubrimos",
        form_2p: "descubrís",
        form_3p: "descubren",
        gerund: "descubriendo",
        gerund_english: "discovering",
        pastparticiple: "descubierto",
        pastparticiple_english: "discovered"
    },
    {
        infinitive: "permitir",
        infinitive_english: "to permit, allow",
        mood: "Indicativo",
        mood_english: "Indicative",
        tense: "Presente",
        tense_english: "Present",
        verb_english: "I permit, am permitting",
        form_1s: "permito",
        form_2s: "permites",
        form_3s: "permite",
        form_1p: "permitimos",
        form_2p: "permitís",
        form_3p: "permiten",
        gerund: "permitiendo",
        gerund_english: "permitting",
        pastparticiple: "permitido",
        pastparticiple_english: "permitted"
    },
    {
        infinitive: "admitir",
        infinitive_english: "to admit, accept, allow, recognize",
        mood: "Indicativo",
        mood_english: "Indicative",
        tense: "Presente",
        tense_english: "Present",
        verb_english: "I admit, am admitting",
        form_1s: "admito",
        form_2s: "admites",
        form_3s: "admite",
        form_1p: "admitimos",
        form_2p: "admitís",
        form_3p: "admiten",
        gerund: "admitiendo",
        gerund_english: "admitting",
        pastparticiple: "admitido",
        pastparticiple_english: "admitted"
    },
    {
        infinitive: "recibir",
        infinitive_english: "to receive; to welcome, greet",
        mood: "Indicativo",
        mood_english: "Indicative",
        tense: "Presente",
        tense_english: "Present",
        verb_english: "I receive, am receiving",
        form_1s: "recibo",
        form_2s: "recibes",
        form_3s: "recibe",
        form_1p: "recibimos",
        form_2p: "recibís",
        form_3p: "reciben",
        gerund: "recibiendo",
        gerund_english: "receiving",
        pastparticiple: "recibido",
        pastparticiple_english: "received"
    },
    {
        infinitive: "asistir",
        infinitive_english: "to attend",
        mood: "Indicativo",
        mood_english: "Indicative",
        tense: "Presente",
        tense_english: "Present",
        verb_english: "I attend, am attending",
        form_1s: "asisto",
        form_2s: "asistes",
        form_3s: "asiste",
        form_1p: "asistimos",
        form_2p: "asistís",
        form_3p: "asisten",
        gerund: "asistiendo",
        gerund_english: "attending",
        pastparticiple: "asistido",
        pastparticiple_english: "attended"
    },
    {
        infinitive: "subir",
        infinitive_english: "to go up, rise, move up, climb; to lift up, raise up",
        mood: "Indicativo",
        mood_english: "Indicative",
        tense: "Presente",
        tense_english: "Present",
        verb_english: "I go up, am going up",
        form_1s: "subo",
        form_2s: "subes",
        form_3s: "sube",
        form_1p: "subimos",
        form_2p: "subís",
        form_3p: "suben",
        gerund: "subiendo",
        gerund_english: "going up",
        pastparticiple: "subido",
        pastparticiple_english: "went up"
    },
    {
        infinitive: "cubrir",
        infinitive_english: "to cover",
        mood: "Indicativo",
        mood_english: "Indicative",
        tense: "Presente",
        tense_english: "Present",
        verb_english: "I cover, am covering",
        form_1s: "cubro",
        form_2s: "cubres",
        form_3s: "cubre",
        form_1p: "cubrimos",
        form_2p: "cubrís",
        form_3p: "cubren",
        gerund: "cubriendo",
        gerund_english: "covering",
        pastparticiple: "cubierto",
        pastparticiple_english: "covered"
    },
    {
        infinitive: "sufrir",
        infinitive_english: "to suffer",
        mood: "Indicativo",
        mood_english: "Indicative",
        tense: "Presente",
        tense_english: "Present",
        verb_english: "I suffer, am suffering",
        form_1s: "sufro",
        form_2s: "sufres",
        form_3s: "sufre",
        form_1p: "sufrimos",
        form_2p: "sufrís",
        form_3p: "sufren",
        gerund: "sufriendo",
        gerund_english: "suffering",
        pastparticiple: "sufrido",
        pastparticiple_english: "suffered"
    },
    {
        infinitive: "decidir",
        infinitive_english: "to decide",
        mood: "Indicativo",
        mood_english: "Indicative",
        tense: "Presente",
        tense_english: "Present",
        verb_english: "I decide, am deciding",
        form_1s: "decido",
        form_2s: "decides",
        form_3s: "decide",
        form_1p: "decidimos",
        form_2p: "decidís",
        form_3p: "deciden",
        gerund: "decidiendo",
        gerund_english: "deciding",
        pastparticiple: "decidido",
        pastparticiple_english: "decided"
    },
    {
        infinitive: "unir",
        infinitive_english: "to unite, to join",
        mood: "Indicativo",
        mood_english: "Indicative",
        tense: "Presente",
        tense_english: "Present",
        verb_english: "I unite, am uniting",
        form_1s: "uno",
        form_2s: "unes",
        form_3s: "une",
        form_1p: "unimos",
        form_2p: "unís",
        form_3p: "unen",
        gerund: "uniendo",
        gerund_english: "uniting",
        pastparticiple: "unido",
        pastparticiple_english: "united"
    },
    {
        infinitive: "describir",
        infinitive_english: "to describe",
        mood: "Indicativo",
        mood_english: "Indicative",
        tense: "Presente",
        tense_english: "Present",
        verb_english: "I describe, am describing",
        form_1s: "describo",
        form_2s: "describes",
        form_3s: "describe",
        form_1p: "describimos",
        form_2p: "describís",
        form_3p: "describen",
        gerund: "describiendo",
        gerund_english: "describing",
        pastparticiple: "descrito",
        pastparticiple_english: "described"
    },
    {
        infinitive: "vivir",
        infinitive_english: "to live",
        mood: "Indicativo",
        mood_english: "Indicative",
        tense: "Presente",
        tense_english: "Present",
        verb_english: "I live, am living",
        form_1s: "vivo",
        form_2s: "vives",
        form_3s: "vive",
        form_1p: "vivimos",
        form_2p: "vivís",
        form_3p: "viven",
        gerund: "viviendo",
        gerund_english: "living",
        pastparticiple: "vivido",
        pastparticiple_english: "lived"
    },
]

export default presentData

