const presentData = [
    {
        infinitive: 'correr',
        infinitive_english: 'to run',
        mood: 'Indicativo',
        mood_english: 'Indicative',
        tense: 'Presente',
        tense_english: 'Present',
        verb_english: 'I run, am running',
        form_1s: 'corro',
        form_2s: 'corres',
        form_3s: 'corre',
        form_1p: 'corremos',
        form_2p: 'corréis',
        form_3p: 'corren',
        gerund: 'corriendo',
        gerund_english: 'running',
        pastparticiple: 'corrido',
        pastparticiple_english: 'run'
    },
    {
        infinitive: 'venir',
        infinitive_english: 'to come',
        mood: 'Indicativo',
        mood_english: 'Indicative',
        tense: 'Presente',
        tense_english: 'Present',
        verb_english: 'I come, am coming',
        form_1s: 'vengo',
        form_2s: 'vienes',
        form_3s: 'viene',
        form_1p: 'venimos',
        form_2p: 'venís',
        form_3p: 'vienen',
        gerund: 'viniendo',
        gerund_english: 'coming',
        pastparticiple: 'venido',
        pastparticiple_english: 'come'
    },
    {
        infinitive: 'decir',
        infinitive_english: 'to say, tell',
        mood: 'Indicativo',
        mood_english: 'Indicative',
        tense: 'Presente',
        tense_english: 'Present',
        verb_english: 'I say, am saying',
        form_1s: 'digo',
        form_2s: 'dices',
        form_3s: 'dice',
        form_1p: 'decimos',
        form_2p: 'decís',
        form_3p: 'dicen',
        gerund: 'diciendo',
        gerund_english: 'saying',
        pastparticiple: 'dicho',
        pastparticiple_english: 'said'
    },
    {
        infinitive: 'poder',
        infinitive_english: 'to be able, can',
        mood: 'Indicativo',
        mood_english: 'Indicative',
        tense: 'Presente',
        tense_english: 'Present',
        verb_english: 'I am able, can',
        form_1s: 'puedo',
        form_2s: 'puedes',
        form_3s: 'puede',
        form_1p: 'podemos',
        form_2p: 'podéis',
        form_3p: 'pueden',
        gerund: 'pudiendo',
        gerund_english: 'being able',
        pastparticiple: 'podido',
        pastparticiple_english: 'been able'
    },
    {
        infinitive: 'dar',
        infinitive_english: 'to give',
        mood: 'Indicativo',
        mood_english: 'Indicative',
        tense: 'Presente',
        tense_english: 'Present',
        verb_english: 'I give, am giving',
        form_1s: 'doy',
        form_2s: 'das',
        form_3s: 'da',
        form_1p: 'damos',
        form_2p: 'dais',
        form_3p: 'dan',
        gerund: 'dando',
        gerund_english: 'giving',
        pastparticiple: 'dado',
        pastparticiple_english: 'given'
    },
    {
        infinitive: 'ver',
        infinitive_english: 'to see',
        mood: 'Indicativo',
        mood_english: 'Indicative',
        tense: 'Presente',
        tense_english: 'Present',
        verb_english: 'I see, am seeing',
        form_1s: 'veo',
        form_2s: 'ves',
        form_3s: 've',
        form_1p: 'vemos',
        form_2p: 'veis',
        form_3p: 'ven',
        gerund: 'viendo',
        gerund_english: 'seeing',
        pastparticiple: 'visto',
        pastparticiple_english: 'seen'
    },
    {
        infinitive: 'saber',
        infinitive_english: 'to know',
        mood: 'Indicativo',
        mood_english: 'Indicative',
        tense: 'Presente',
        tense_english: 'Present',
        verb_english: 'I know',
        form_1s: 'sé',
        form_2s: 'sabes',
        form_3s: 'sabe',
        form_1p: 'sabemos',
        form_2p: 'sabéis',
        form_3p: 'saben',
        gerund: 'sabiendo',
        gerund_english: 'knowing',
        pastparticiple: 'sabido',
        pastparticiple_english: 'known'
    },
    {
        infinitive: 'hablar',
        infinitive_english: 'to speak',
        mood: 'Indicativo',
        mood_english: 'Indicative',
        tense: 'Presente',
        tense_english: 'Present',
        verb_english: 'I speak, am speaking',
        form_1s: 'hablo',
        form_2s: 'hablas',
        form_3s: 'habla',
        form_1p: 'hablamos',
        form_2p: 'habláis',
        form_3p: 'hablan',
        gerund: 'hablando',
        gerund_english: 'speaking',
        pastparticiple: 'hablado',
        pastparticiple_english: 'spoken'
    },
    {
        infinitive: 'estar',
        infinitive_english: 'to be',
        mood: 'Indicativo',
        mood_english: 'Indicative',
        tense: 'Presente',
        tense_english: 'Present',
        verb_english: 'I am',
        form_1s: 'estoy',
        form_2s: 'estás',
        form_3s: 'está',
        form_1p: 'estamos',
        form_2p: 'estáis',
        form_3p: 'están',
        gerund: 'estando',
        gerund_english: 'being',
        pastparticiple: 'estado',
        pastparticiple_english: 'been'
    },
    {
        infinitive: 'ser',
        infinitive_english: 'to be',
        mood: 'Indicativo',
        mood_english: 'Indicative',
        tense: 'Presente',
        tense_english: 'Present',
        verb_english: 'I am',
        form_1s: 'soy',
        form_2s: 'eres',
        form_3s: 'es',
        form_1p: 'somos',
        form_2p: 'sois',
        form_3p: 'son',
        gerund: 'siendo',
        gerund_english: 'being',
        pastparticiple: 'sido',
        pastparticiple_english: 'been'
    },
    {
        infinitive: 'tener',
        infinitive_english: 'to have',
        mood: 'Indicativo',
        mood_english: 'Indicative',
        tense: 'Presente',
        tense_english: 'Present',
        verb_english: 'I have, am having',
        form_1s: 'tengo',
        form_2s: 'tienes',
        form_3s: 'tiene',
        form_1p: 'tenemos',
        form_2p: 'tenéis',
        form_3p: 'tienen',
        gerund: 'teniendo',
        gerund_english: 'having',
        pastparticiple: 'tenido',
        pastparticiple_english: 'had'
    },
    {
        infinitive: 'hacer',
        infinitive_english: 'to do, make',
        mood: 'Indicativo',
        mood_english: 'Indicative',
        tense: 'Presente',
        tense_english: 'Present',
        verb_english: 'I do, am doing',
        form_1s: 'hago',
        form_2s: 'haces',
        form_3s: 'hace',
        form_1p: 'hacemos',
        form_2p: 'hacéis',
        form_3p: 'hacen',
        gerund: 'haciendo',
        gerund_english: 'doing',
        pastparticiple: 'hecho',
        pastparticiple_english: 'done'
    },
    {
        infinitive: 'ir',
        infinitive_english: 'to go',
        mood: 'Indicativo',
        mood_english: 'Indicative',
        tense: 'Presente',
        tense_english: 'Present',
        verb_english: 'I go, am going',
        form_1s: 'voy',
        form_2s: 'vas',
        form_3s: 'va',
        form_1p: 'vamos',
        form_2p: 'vais',
        form_3p: 'van',
        gerund: 'yendo',
        gerund_english: 'going',
        pastparticiple: 'ido',
        pastparticiple_english: 'gone'
    },
]

export default presentData

